# Generated by Django 5.1.3 on 2025-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='users/user_default.png', upload_to='users/'),
        ),
    ]
