# Generated by Django 5.1.3 on 2025-01-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song_uploader_alter_song_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casette',
            new_name='Cassette',
        ),
        migrations.AddField(
            model_name='song',
            name='cassette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cassette'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
