# Generated by Django 5.1.3 on 2025-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_casette_cassette_song_cassette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
