# Generated by Django 5.1.3 on 2025-01-12 06:43

import django.core.validators
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cassette_accent_color_alter_cassette_color1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='source',
            field=models.FileField(upload_to=main_app.models.get_audio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'ogg', 'wav', 'flac', 'm4a'])]),
        ),
    ]
